### ISSUE TITLE
What is the purpose of the LED at ping +12V and LED

### ISSUE THREAD

**Issue by Elektrofix-OL** [SmartEVSE/SmartEVSE-2#47]
I have updated my smartEVSE V2.02 to version 2.30 because I want to use the solar function.
Between +12V ==> I/O1 (LED) I have an LED and between I/O2 (sw) ==> GND I have switched the button.
I can't figure out how the LED works, it's always on, regardless of whether I'm charging solar, smart or normal.
The button works perfectly.

Greetings from Oldenburg (Odlb) 

Ps: sorry, translate whit google.

**Comment by mstegen** [comment]
Then you probably have an older SmartEVSE hardware revision. If it says 1 instead of LED on the circuit board, then there is no mosfet on this output pin.
You can add a general purpose N-channel mosfet to this output pin, which then can drive the LED correctly. 
I used a BSS138 on the SmartESVE v2.2

Connect the gate to the output pin, and the source to GND. you can connect the drain to the LED.
