### ISSUE TITLE
Using RS485 <--> ETH <--> RS485 between SmartEVSE and Sensorbox

### ISSUE THREAD

**Issue by GerardFianen** [SmartEVSE/SmartEVSE-2#8]
Solved.

**Comment by jimon** [comment]
If someone else needs this, I was able to partially solve this with two mikrotik KNOT devices and one RPi because currently KNOT's cannot pass modbus master commands (they just ignore it), more info https://forum.mikrotik.com/viewtopic.php?p=875143 
And here the code for the proxy app I made for RPi https://github.com/jimon/evseproxy

There are probably some other RS485<->ETH bridges on the market that can pass master commands transparently.
